env:
  browser: true
  commonjs: true
  es6: true
  jasmine: true
extends:
  - 'eslint:recommended'
  - 'plugin:jasmine/recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
parser: 'babel-eslint'
parserOptions:
  allowImportExportEverywhere: true
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jasmine
rules:
  camelcase: 0
  arrow-body-style: 0
  react/no-multi-comp: 0
  import/imports-first: 0
  import/extensions: 0
  arrow-parens: 0
  import/prefer-default-export: 0
  import/newline-after-import: 0
  jsx-a11y/label-has-for: 0
  react/forbid-prop-types: 0
  no-did-mount-set-state: 0
  jsx-a11y/no-static-element-interactions: 0
  class-methods-use-this: 0
  import/no-extraneous-dependencies: 0
  no-new: 0

  jsx-a11y/href-no-hash: 0
  jsx-a11y/anchor-is-valid: ['warn', { 'aspects': ['invalidHref'] }]
